name:                24ParserCombinators
version:             0.1.0.0
github:              "githubuser/24ParserCombinators"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/24ParserCombinators#readme>

dependencies:
- base >= 4.7 && < 5
- trifecta
- raw-strings-qq
- bytestring
- containers
- hspec
- text
- attoparsec
- parsec
- aeson
- sort
- parser-combinators
- QuickCheck
- random

library:
  source-dirs:
    - src
    - .

executables:
  24ParserCombinators-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 24ParserCombinators

tests:
  24ParserCombinators-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 24ParserCombinators
